In [ ]:
import pandas as pd
import numpy as np

In [ ]:
## importing data train and test data file

zbay_traindata = pd.read_csv(r"C:\akshay\hackthon\train.csv",engine = "python")
zbay_testdata = pd.read_csv(r"C:\akshay\hackthon\test.csv",engine = "python")
zbay_traindata.head()

In [94]:
zbay_traindata.shape

(237609, 7)

In [95]:
zbay_testdata.shape

(90675, 6)

In [96]:
zbay_traindata.isnull().sum()

impression_id      0
impression_time    0
user_id            0
app_code           0
os_version         0
is_4G              0
is_click           0
dtype: int64

In [97]:
zbay_traindata.dtypes

impression_id      object
impression_time    object
user_id             int64
app_code            int64
os_version         object
is_4G               int64
is_click            int64
dtype: object

In [98]:
zbay_traindata_df = pd.DataFrame.copy(zbay_traindata) ##copied the file

In [99]:
zbay_traindata_df = zbay_traindata_df.drop(["user_id"],axis =1)


In [100]:
zbay_traindata_df.isnull().sum()


impression_id      0
impression_time    0
app_code           0
os_version         0
is_4G              0
is_click           0
dtype: int64

In [101]:

#creating the list of categorical data
colnames = ["impression_id","impression_time","os_version"]
colnames

['impression_id', 'impression_time', 'os_version']

In [102]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

for x in colnames:
    zbay_traindata_df[x]= le.fit_transform(zbay_traindata_df[x])
    
zbay_traindata_df.head()


#0  -----> not click
#1------ click

impression_id  impression_time  app_code  os_version  is_4G  is_click
0         182392                0       422           2      0         0
1          64948                1       467           1      1         1
2         104489                2       259           0      1         0
3         131623                2       244           1      1         0
4          22778                2       473           1      0         0

In [103]:
zbay_traindata_df.dtypes

impression_id      int32
impression_time    int32
app_code           int64
os_version         int32
is_4G              int64
is_click           int64
dtype: object

In [104]:

#creating the list of categorical data
colnames = ["impression_id","impression_time","os_version"]
colnames

from sklearn import preprocessing

le = preprocessing.LabelEncoder()

for x in colnames:
    zbay_testdata[x]= le.fit_transform(zbay_testdata[x])
    
zbay_testdata.head()

impression_id  impression_time  user_id  app_code  os_version  is_4G
0          60031             1592    44754       127           1      1
1          71691             1593    29656        44           1      0
2           7193             1594    25234       296           1      1
3          20595             1595    22988       207           1      1
4          67610             1596    35431       242           1      1

In [105]:
zbay_testdata.dtypes

impression_id      int64
impression_time    int64
user_id            int64
app_code           int64
os_version         int64
is_4G              int64
dtype: object

In [106]:
#creating X and Y

X = zbay_traindata_df.values[:,:-1]
Y = zbay_traindata_df.values[:,-1]

Y = Y.astype(int)

In [110]:
X_test = zbay_testdata.values[:,:]

In [113]:

from sklearn.preprocessing import StandardScaler

# dont fit scalar object on scaling data.Fit function only traning data and use the same scale to transform the training and scaling data

scaler = StandardScaler()

scaler.fit(X)

X = scaler.transform(X)

print(X)

[[ 0.92704945 -1.85970737  1.27872035  1.49756775 -0.75213688]
 [-0.78516662 -1.85960608  1.61152778  0.01678284  1.32954524]
 [-0.20869839 -1.85950478  0.07321785 -1.46400207  1.32954524]
 ...
 [ 0.18930832  1.8333599   0.29508948  1.49756775 -0.75213688]
 [ 0.38643097  1.83346119  1.00507868  1.49756775 -0.75213688]
 [ 0.51850214  1.83346119  0.64268836  1.49756775  1.32954524]]


C:\Users\akshay.vilayatkar.vc\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\akshay.vilayatkar.vc\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [114]:
#creating the model

from sklearn import svm

svc_model =svm.SVC(kernel = "rbf" ,C=1.0 ,gamma= 0.1)

svc_model.fit(X,Y)

y_pred = svc_model.predict(X_test)



ValueError: X.shape[1] = 6 should be equal to 5, the number of features at training time

In [ ]:
print(list(Y_pred))